declare const styles: {
    placeholder: string;
    placeholder__icon: string;
    placeholder__iconText: string;
    placeholder__description: string;
    swiper_button_prev: string;
    swiper_button_next: string;
    bannerSwipper: string;
    bannerSwipper__ButtonPrev: string;
    bannerSwipper__ButtonNext: string;
    bannerPrincipal: string;
    container: string;
    bannerPrincipal__header: string;
    nextButtonClassName: string;
    prevButtonClassName: string;
    carouselContent: string;
    carouselButtonsContainer: string;
    section_dynamics__banner__description: string;
    section_header: string;
    section_header__banner: string;
    banner__content: string;
    controllerBanner: string;
    bannerAction: string;
    actionText: string;
    bannerCard: string;
    cardImageContainer: string;
    cardBrief: string;
    cardSubTitle: string;
    cardDate: string;
    cardTitle: string;
    cardImage: string;
    cardCta: string;
};
export default styles;
//# sourceMappingURL=BannerPrincipal.module.scss.d.ts.map